version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - appId=
      - appSecret=
      - masterId=
      - verToken=
      - eventKey=
    ports:
      - 50241:8080
    volumes:
      - ./data:/app/data